from . import res_users
from . import sale_order
from . import hr_employee
from . import hr_expense
from . import purchase_order
from . import stock_picking
from . import stock_scrap
from . import account_move
from . import mrp_production
from . import stock_adjustment
from . import purchase_stock_requisition_extend
from . import submmission_quotation_extend
from . import mrp_ro_produce_extend
