from . import pos
from . import account_move
from . import account_bank_statement
from . import product
from . import stock_picking
from . import stock_inventory
from . import stock_scrap
from . import stock_landed_costs
from . import purchase
from . import account_payment
from . import shop_to_take
from . import account_analytic_account
