from . import product
from . import product_pricelist
from . import sale
from . import purchase
from . import purchase_requisition_line_original_extend
from . import purchase_requisitions
from . import stock_move
from . import stock_move_line
from . import stock_rule
from . import account_move
from . import stock_picking
from . import stock_orderpoint
from . import stock_scrap
from . import stock_quant
from . import res_config_settings
from . import stock_requestion
from . import mrp_production
from . import mrp_bom
from . import mrp_bom_cost
from . import whole_sale_requisition
from . import submission_quotation

