{
    'name': 'Multi UOM',
    'category': 'Inventory',
    'author': 'Asia Matrix',
    'version': '4.2',
    'depends': [
        'stock',
        'sale_stock',
        'purchase_stock',
        'nilar_purchase_requisition',
        'stock_account',
        'purchase_extend',
        'stock_requestion',
        'mrp_to_journal',
        'web',
        'purchase_requisition',
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'data/decimal_precision.xml',
        'views/product_views.xml',
        'views/sale_order_views.xml',
        'views/purchase_order_views.xml',
        'views/purchase_requisitions_views.xml',
        'views/stock_views.xml',
        'views/account_move_views.xml',
        'views/res_config_settings_views.xml',
        'views/stock_requestion_views.xml',
        'views/mrp_bom_form_view.xml',
        'views/mrp_production_form_view.xml',
        'views/whole_sale_requisition_view.xml',
        'views/mrp_bom_cost_views.xml',
        'views/submission_of_quotaion_view.xml',
        'views/sale_quotation_template_view.xml',
        'wizards/stock_picking_return.xml',
            ],
    'assets': {
        'web.assets_backend': [
            'multi_uom/static/src/js/list.js',
            'multi_uom/static/src/js/multi_should_consume_qty.js',
            'multi_uom/static/src/css/list.css',
        ],
    },
    'installable': True,
    'license': 'LGPL-3',
}
